# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlCenter.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WXCGame(object):
    def setupUi(self, WXCGame):
        WXCGame.setObjectName("WXCGame")
        WXCGame.resize(680, 550)
        WXCGame.setMinimumSize(QtCore.QSize(680, 550))
        WXCGame.setMaximumSize(QtCore.QSize(680, 550))
        self.verticalLayout = QtWidgets.QVBoxLayout(WXCGame)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(WXCGame)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.lineEdit_search.setFont(font)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(WXCGame)
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(WXCGame)
        self.tableWidget.setMinimumSize(QtCore.QSize(280, 450))
        self.tableWidget.setMaximumSize(QtCore.QSize(280, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_3.setStretch(0, 6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_teacher = QtWidgets.QVBoxLayout()
        self.verticalLayout_teacher.setObjectName("verticalLayout_teacher")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_teacher.addItem(spacerItem)
        self.comboBox_User = QtWidgets.QComboBox(WXCGame)
        self.comboBox_User.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_User.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_User.setFont(font)
        self.comboBox_User.setObjectName("comboBox_User")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.verticalLayout_teacher.addWidget(self.comboBox_User)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_teacher.addItem(spacerItem1)
        self.lineEdit_teacher_password = QtWidgets.QLineEdit(WXCGame)
        self.lineEdit_teacher_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_teacher_password.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_teacher_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_teacher_password.setObjectName("lineEdit_teacher_password")
        self.verticalLayout_teacher.addWidget(self.lineEdit_teacher_password)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_teacher.addItem(spacerItem2)
        self.pushButton_confirm = QtWidgets.QPushButton(WXCGame)
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(365, 30))
        self.pushButton_confirm.setMaximumSize(QtCore.QSize(999999, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.verticalLayout_teacher.addWidget(self.pushButton_confirm, 0,
                                              QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.verticalLayout_teacher.setStretch(0, 1)
        self.verticalLayout_teacher.setStretch(1, 1)
        self.verticalLayout_teacher.setStretch(2, 1)
        self.verticalLayout_teacher.setStretch(3, 1)
        self.verticalLayout_teacher.setStretch(4, 1)
        self.verticalLayout_teacher.setStretch(5, 1)
        self.horizontalLayout_19.addLayout(self.verticalLayout_teacher)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_Avatar = QtWidgets.QLabel(WXCGame)
        self.label_Avatar.setText("")
        self.label_Avatar.setObjectName("label_Avatar")
        self.horizontalLayout_20.addWidget(self.label_Avatar)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19.setStretch(0, 2)
        self.horizontalLayout_19.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.stackedWidget = QtWidgets.QStackedWidget(WXCGame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Teacher = QtWidgets.QWidget()
        self.page_Teacher.setObjectName("page_Teacher")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_Teacher)
        self.horizontalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBox_TeacherClass = QtWidgets.QComboBox(self.page_Teacher)
        self.comboBox_TeacherClass.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_TeacherClass.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_TeacherClass.setObjectName("comboBox_TeacherClass")
        self.horizontalLayout_11.addWidget(self.comboBox_TeacherClass)
        self.comboBox_TeacherStudent = QtWidgets.QComboBox(self.page_Teacher)
        self.comboBox_TeacherStudent.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_TeacherStudent.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_TeacherStudent.setObjectName("comboBox_TeacherStudent")
        self.horizontalLayout_11.addWidget(self.comboBox_TeacherStudent)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_task = QtWidgets.QHBoxLayout()
        self.horizontalLayout_task.setObjectName("horizontalLayout_task")
        self.comboBox_task = QtWidgets.QComboBox(self.page_Teacher)
        self.comboBox_task.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_task.setMaximumSize(QtCore.QSize(8000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_task.setFont(font)
        self.comboBox_task.setObjectName("comboBox_task")
        self.comboBox_task.addItem("")
        self.comboBox_task.addItem("")
        self.comboBox_task.addItem("")
        self.comboBox_task.addItem("")
        self.horizontalLayout_task.addWidget(self.comboBox_task)
        self.pushButton_finish = QtWidgets.QPushButton(self.page_Teacher)
        self.pushButton_finish.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_finish.setMaximumSize(QtCore.QSize(600000, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_finish.setFont(font)
        self.pushButton_finish.setObjectName("pushButton_finish")
        self.horizontalLayout_task.addWidget(self.pushButton_finish)
        self.horizontalLayout_task.setStretch(0, 3)
        self.horizontalLayout_task.setStretch(1, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_task)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_Teacher)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.classing = QtWidgets.QWidget()
        self.classing.setObjectName("classing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.classing)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.classing)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_checkpoint1 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_checkpoint1.setFont(font)
        self.radioButton_checkpoint1.setObjectName("radioButton_checkpoint1")
        self.horizontalLayout_6.addWidget(self.radioButton_checkpoint1)
        self.radioButton_checkpoint2 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_checkpoint2.setFont(font)
        self.radioButton_checkpoint2.setObjectName("radioButton_checkpoint2")
        self.horizontalLayout_6.addWidget(self.radioButton_checkpoint2)
        self.radioButton_checkpoint3 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_checkpoint3.setFont(font)
        self.radioButton_checkpoint3.setObjectName("radioButton_checkpoint3")
        self.horizontalLayout_6.addWidget(self.radioButton_checkpoint3)
        self.radioButton_checkpoint4 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_checkpoint4.setFont(font)
        self.radioButton_checkpoint4.setObjectName("radioButton_checkpoint4")
        self.horizontalLayout_6.addWidget(self.radioButton_checkpoint4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_storyCheckPoint1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_storyCheckPoint1.setFont(font)
        self.label_storyCheckPoint1.setObjectName("label_storyCheckPoint1")
        self.horizontalLayout_15.addWidget(self.label_storyCheckPoint1, 0, QtCore.Qt.AlignHCenter)
        self.label_checkpoint1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_checkpoint1.setFont(font)
        self.label_checkpoint1.setText("")
        self.label_checkpoint1.setObjectName("label_checkpoint1")
        self.horizontalLayout_15.addWidget(self.label_checkpoint1, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_storyCheckPoint2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_storyCheckPoint2.setFont(font)
        self.label_storyCheckPoint2.setObjectName("label_storyCheckPoint2")
        self.horizontalLayout_13.addWidget(self.label_storyCheckPoint2, 0, QtCore.Qt.AlignHCenter)
        self.label_checkpoint2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_checkpoint2.setFont(font)
        self.label_checkpoint2.setText("")
        self.label_checkpoint2.setObjectName("label_checkpoint2")
        self.horizontalLayout_13.addWidget(self.label_checkpoint2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_storyCheckPoint3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_storyCheckPoint3.setFont(font)
        self.label_storyCheckPoint3.setObjectName("label_storyCheckPoint3")
        self.horizontalLayout_17.addWidget(self.label_storyCheckPoint3, 0, QtCore.Qt.AlignHCenter)
        self.label_checkpoint3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_checkpoint3.setFont(font)
        self.label_checkpoint3.setText("")
        self.label_checkpoint3.setObjectName("label_checkpoint3")
        self.horizontalLayout_17.addWidget(self.label_checkpoint3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_storyCheckPoint4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_storyCheckPoint4.setFont(font)
        self.label_storyCheckPoint4.setObjectName("label_storyCheckPoint4")
        self.horizontalLayout_16.addWidget(self.label_storyCheckPoint4, 0, QtCore.Qt.AlignHCenter)
        self.label_checkpoint4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_checkpoint4.setFont(font)
        self.label_checkpoint4.setText("")
        self.label_checkpoint4.setObjectName("label_checkpoint4")
        self.horizontalLayout_16.addWidget(self.label_checkpoint4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.verticalLayout_10.setStretch(2, 1)
        self.verticalLayout_10.setStretch(4, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_4.addWidget(self.widget)
        self.stackedWidget_2.addWidget(self.classing)
        self.free = QtWidgets.QWidget()
        self.free.setObjectName("free")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.free)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_S = QtWidgets.QRadioButton(self.free)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_S.setFont(font)
        self.radioButton_S.setObjectName("radioButton_S")
        self.horizontalLayout_5.addWidget(self.radioButton_S)
        self.radioButton_SS = QtWidgets.QRadioButton(self.free)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_SS.setFont(font)
        self.radioButton_SS.setObjectName("radioButton_SS")
        self.horizontalLayout_5.addWidget(self.radioButton_SS)
        self.radioButton_SSS = QtWidgets.QRadioButton(self.free)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.radioButton_SSS.setFont(font)
        self.radioButton_SSS.setObjectName("radioButton_SSS")
        self.horizontalLayout_5.addWidget(self.radioButton_SSS)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_story_2 = QtWidgets.QLabel(self.free)
        self.label_story_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_story_2.setFont(font)
        self.label_story_2.setObjectName("label_story_2")
        self.horizontalLayout_14.addWidget(self.label_story_2, 0, QtCore.Qt.AlignHCenter)
        self.label_action1 = QtWidgets.QLabel(self.free)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_action1.setFont(font)
        self.label_action1.setText("")
        self.label_action1.setObjectName("label_action1")
        self.horizontalLayout_14.addWidget(self.label_action1, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_challenge_2 = QtWidgets.QLabel(self.free)
        self.label_challenge_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_challenge_2.setFont(font)
        self.label_challenge_2.setObjectName("label_challenge_2")
        self.horizontalLayout_7.addWidget(self.label_challenge_2, 0, QtCore.Qt.AlignHCenter)
        self.label_action2 = QtWidgets.QLabel(self.free)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_action2.setFont(font)
        self.label_action2.setText("")
        self.label_action2.setObjectName("label_action2")
        self.horizontalLayout_7.addWidget(self.label_action2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_bounty = QtWidgets.QLabel(self.free)
        self.label_bounty.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_bounty.setFont(font)
        self.label_bounty.setObjectName("label_bounty")
        self.horizontalLayout_8.addWidget(self.label_bounty, 0, QtCore.Qt.AlignHCenter)
        self.label_action3 = QtWidgets.QLabel(self.free)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_action3.setFont(font)
        self.label_action3.setText("")
        self.label_action3.setObjectName("label_action3")
        self.horizontalLayout_8.addWidget(self.label_action3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.stackedWidget_2.addWidget(self.free)
        self.verticalLayout_7.addWidget(self.stackedWidget_2)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_Teacher)
        self.page_StudentManager = QtWidgets.QWidget()
        self.page_StudentManager.setObjectName("page_StudentManager")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_StudentManager)
        self.horizontalLayout_12.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.comboBox_Teacher = QtWidgets.QComboBox(self.page_StudentManager)
        self.comboBox_Teacher.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_Teacher.setFont(font)
        self.comboBox_Teacher.setObjectName("comboBox_Teacher")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.comboBox_Teacher.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_Teacher)
        self.comboBox_Class = QtWidgets.QComboBox(self.page_StudentManager)
        self.comboBox_Class.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_Class.setFont(font)
        self.comboBox_Class.setObjectName("comboBox_Class")
        self.horizontalLayout_10.addWidget(self.comboBox_Class)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.pushButton_PublishStoryTask = QtWidgets.QPushButton(self.page_StudentManager)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_PublishStoryTask.setFont(font)
        self.pushButton_PublishStoryTask.setObjectName("pushButton_PublishStoryTask")
        self.verticalLayout_8.addWidget(self.pushButton_PublishStoryTask)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.pushButton_PublishChallengeTask = QtWidgets.QPushButton(self.page_StudentManager)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_PublishChallengeTask.setFont(font)
        self.pushButton_PublishChallengeTask.setObjectName("pushButton_PublishChallengeTask")
        self.verticalLayout_8.addWidget(self.pushButton_PublishChallengeTask)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.pushButton_PublishBountyTask = QtWidgets.QPushButton(self.page_StudentManager)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_PublishBountyTask.setFont(font)
        self.pushButton_PublishBountyTask.setObjectName("pushButton_PublishBountyTask")
        self.verticalLayout_8.addWidget(self.pushButton_PublishBountyTask)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_Student = QtWidgets.QComboBox(self.page_StudentManager)
        self.comboBox_Student.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_Student.setFont(font)
        self.comboBox_Student.setObjectName("comboBox_Student")
        self.verticalLayout_9.addWidget(self.comboBox_Student)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_finishStoryTask = QtWidgets.QPushButton(self.page_StudentManager)
        self.pushButton_finishStoryTask.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_finishStoryTask.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_finishStoryTask.setFont(font)
        self.pushButton_finishStoryTask.setObjectName("pushButton_finishStoryTask")
        self.verticalLayout_14.addWidget(self.pushButton_finishStoryTask, 0, QtCore.Qt.AlignVCenter)
        self.pushButton_finishChallengeTask = QtWidgets.QPushButton(self.page_StudentManager)
        self.pushButton_finishChallengeTask.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_finishChallengeTask.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_finishChallengeTask.setFont(font)
        self.pushButton_finishChallengeTask.setObjectName("pushButton_finishChallengeTask")
        self.verticalLayout_14.addWidget(self.pushButton_finishChallengeTask, 0, QtCore.Qt.AlignVCenter)
        self.pushButton_finishBountyTask = QtWidgets.QPushButton(self.page_StudentManager)
        self.pushButton_finishBountyTask.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_finishBountyTask.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_finishBountyTask.setFont(font)
        self.pushButton_finishBountyTask.setObjectName("pushButton_finishBountyTask")
        self.verticalLayout_14.addWidget(self.pushButton_finishBountyTask, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_29.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_storyTaskFinishStatus = QtWidgets.QLabel(self.page_StudentManager)
        self.label_storyTaskFinishStatus.setMinimumSize(QtCore.QSize(0, 30))
        self.label_storyTaskFinishStatus.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_storyTaskFinishStatus.setFont(font)
        self.label_storyTaskFinishStatus.setObjectName("label_storyTaskFinishStatus")
        self.verticalLayout_15.addWidget(self.label_storyTaskFinishStatus, 0,
                                         QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_challengeTaskFinishStatus = QtWidgets.QLabel(self.page_StudentManager)
        self.label_challengeTaskFinishStatus.setMinimumSize(QtCore.QSize(0, 30))
        self.label_challengeTaskFinishStatus.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_challengeTaskFinishStatus.setFont(font)
        self.label_challengeTaskFinishStatus.setObjectName("label_challengeTaskFinishStatus")
        self.verticalLayout_15.addWidget(self.label_challengeTaskFinishStatus, 0,
                                         QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_bountyTaskFinishStatus = QtWidgets.QLabel(self.page_StudentManager)
        self.label_bountyTaskFinishStatus.setMinimumSize(QtCore.QSize(0, 30))
        self.label_bountyTaskFinishStatus.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_bountyTaskFinishStatus.setFont(font)
        self.label_bountyTaskFinishStatus.setObjectName("label_bountyTaskFinishStatus")
        self.verticalLayout_15.addWidget(self.label_bountyTaskFinishStatus, 0,
                                         QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.horizontalLayout_29.addLayout(self.verticalLayout_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_29)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 9)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.page_StudentManager)
        self.page_blank = QtWidgets.QWidget()
        self.page_blank.setObjectName("page_blank")
        self.stackedWidget.addWidget(self.page_blank)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_submit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_submit.setObjectName("horizontalLayout_submit")
        self.pushButton_discard = QtWidgets.QPushButton(WXCGame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_discard.setFont(font)
        self.pushButton_discard.setObjectName("pushButton_discard")
        self.horizontalLayout_submit.addWidget(self.pushButton_discard)
        self.pushButton_submit = QtWidgets.QPushButton(WXCGame)
        self.pushButton_submit.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_submit.setMaximumSize(QtCore.QSize(999999, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.horizontalLayout_submit.addWidget(self.pushButton_submit)
        self.horizontalLayout_submit.setStretch(0, 1)
        self.horizontalLayout_submit.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_submit)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)

        self.retranslateUi(WXCGame)
        self.comboBox_User.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WXCGame)

    def retranslateUi(self, WXCGame):
        _translate = QtCore.QCoreApplication.translate
        WXCGame.setWindowTitle(_translate("WXCGame", "WXCGame"))
        self.pushButton_search.setText(_translate("WXCGame", "搜索"))
        self.comboBox_User.setItemText(0, _translate("WXCGame", "星智博士"))
        self.comboBox_User.setItemText(1, _translate("WXCGame", "魏泽宇"))
        self.comboBox_User.setItemText(2, _translate("WXCGame", "波波"))
        self.comboBox_User.setItemText(3, _translate("WXCGame", "啾啾"))
        self.comboBox_User.setItemText(4, _translate("WXCGame", "朱敏"))
        self.comboBox_User.setItemText(5, _translate("WXCGame", "刘天鹏"))
        self.comboBox_User.setItemText(6, _translate("WXCGame", "刘攀"))
        self.comboBox_User.setItemText(7, _translate("WXCGame", "薯条老师"))
        self.comboBox_User.setItemText(8, _translate("WXCGame", "糖果老师"))
        self.comboBox_User.setItemText(9, _translate("WXCGame", "徐津"))
        self.lineEdit_teacher_password.setPlaceholderText(_translate("WXCGame", "输入密码"))
        self.pushButton_confirm.setText(_translate("WXCGame", "确认"))
        self.comboBox_task.setItemText(0, _translate("WXCGame", "剧情任务(课上)"))
        self.comboBox_task.setItemText(1, _translate("WXCGame", "剧情任务(课后)"))
        self.comboBox_task.setItemText(2, _translate("WXCGame", "挑战任务"))
        self.comboBox_task.setItemText(3, _translate("WXCGame", "赏金任务"))
        self.pushButton_finish.setText(_translate("WXCGame", "确认完成"))
        self.radioButton_checkpoint1.setText(_translate("WXCGame", "关卡一"))
        self.radioButton_checkpoint2.setText(_translate("WXCGame", "关卡二"))
        self.radioButton_checkpoint3.setText(_translate("WXCGame", "关卡三"))
        self.radioButton_checkpoint4.setText(_translate("WXCGame", "关卡四"))
        self.label_storyCheckPoint1.setText(_translate("WXCGame", "关卡一"))
        self.label_storyCheckPoint2.setText(_translate("WXCGame", "关卡二"))
        self.label_storyCheckPoint3.setText(_translate("WXCGame", "关卡三"))
        self.label_storyCheckPoint4.setText(_translate("WXCGame", "关卡四"))
        self.radioButton_S.setText(_translate("WXCGame", "完成"))
        self.radioButton_SS.setText(_translate("WXCGame", "优秀"))
        self.radioButton_SSS.setText(_translate("WXCGame", "极佳"))
        self.label_story_2.setText(_translate("WXCGame", "剧情任务(课后)"))
        self.label_challenge_2.setText(_translate("WXCGame", "挑战任务"))
        self.label_bounty.setText(_translate("WXCGame", "赏金任务"))
        self.comboBox_Teacher.setItemText(0, _translate("WXCGame", "魏泽宇"))
        self.comboBox_Teacher.setItemText(1, _translate("WXCGame", "波波"))
        self.comboBox_Teacher.setItemText(2, _translate("WXCGame", "啾啾"))
        self.comboBox_Teacher.setItemText(3, _translate("WXCGame", "朱敏"))
        self.comboBox_Teacher.setItemText(4, _translate("WXCGame", "刘天鹏"))
        self.comboBox_Teacher.setItemText(5, _translate("WXCGame", "刘攀"))
        self.comboBox_Teacher.setItemText(6, _translate("WXCGame", "薯条老师"))
        self.comboBox_Teacher.setItemText(7, _translate("WXCGame", "糖果老师"))
        self.comboBox_Teacher.setItemText(8, _translate("WXCGame", "徐津"))
        self.pushButton_PublishStoryTask.setText(_translate("WXCGame", "发布剧情任务"))
        self.pushButton_PublishChallengeTask.setText(_translate("WXCGame", "发布挑战任务"))
        self.pushButton_PublishBountyTask.setText(_translate("WXCGame", "发布赏金任务"))
        self.pushButton_finishStoryTask.setText(_translate("WXCGame", "剧情任务(课后)已完成"))
        self.pushButton_finishChallengeTask.setText(_translate("WXCGame", "挑战任务已完成"))
        self.pushButton_finishBountyTask.setText(_translate("WXCGame", "赏金任务已完成"))
        self.label_storyTaskFinishStatus.setText(_translate("WXCGame", "剧情任务(课后)已完成"))
        self.label_challengeTaskFinishStatus.setText(_translate("WXCGame", "挑战任务已完成"))
        self.label_bountyTaskFinishStatus.setText(_translate("WXCGame", "赏金任务已完成"))
        self.pushButton_discard.setText(_translate("WXCGame", "放弃修改"))
        self.pushButton_submit.setText(_translate("WXCGame", "提交修改"))
